source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

workspace 'SSRequestDirect'
project 'SSRequestDirect'

target 'SSRequestDirect' do
    pod 'SwiftyJSON', '5.0.0'
    pod 'SSRequstHandler', :path => '../../SSRequstHandler'
    pod 'SSRequestDirect', :path => '../../SSRequestDirect'
end
